apiVersion: jenkins.io/v1
kind: SourceRepository
metadata:
  creationTimestamp: null
  labels:
    owner: nonamime
    provider: github
    repository: test
    gitops.jenkins-x.io/pipeline: 'namespaces'
  name: nonamime-test
  namespace: jx
spec:
  httpCloneURL: https://github.com/nonamime/test.git
  org: nonamime
  provider: https://github.com
  providerKind: github
  providerName: github
  repo: test
  scheduler:
    kind: ""
    name: in-repo
  url: https://github.com/nonamime/test
